# Generated by Django 5.2.11 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
