# Generated by Django 5.2.11 on 2026-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_clase_cupo_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
