# Generated by Django 5.1.2 on 2026-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_entrenador_id_alter_socio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('spinning', 'Spinning'), ('crossfit', 'CrossFit'), ('zumba', 'Zumba'), ('boxeo', 'Boxeo')], max_length=100),
        ),
    ]
